plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.motro'
    compileSdk 36
    defaultConfig {
        applicationId "com.example.motro"
        minSdk 24
        targetSdk 35
        versionCode 6
        versionName "1.0.0.6"
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }
    }
    packagingOptions {
        jniLibs {
            useLegacyPackaging true
        }
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

        }
        debug {
            debuggable true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding true
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            if (variant.buildType.name == "release") {
                def versionName = variant.versionName ?: "1.0"
                def timestamp = new Date().format("yyyyMMdd_HHmmss", TimeZone.getTimeZone("GMT+8"))
                def fileName = "app_release_v${versionName}_${timestamp}.apk"
                outputFileName = fileName
            }
        }
    }

}


dependencies {
    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
    implementation project(':ffmpegplayer')
    testImplementation 'junit:junit:4.13.2'
}
