plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    namespace 'com.example.motro.ffmpeg'
    compileSdk 36

    defaultConfig {
        minSdk 24
        targetSdk 31
        consumerProguardFiles 'consumer-rules.pro'

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
        }
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging true
        }
    }

//    compileOptions {
//        sourceCompatibility = JavaVersion.VERSION_17
//        targetCompatibility = JavaVersion.VERSION_17
//    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = 'com.example.motro'
                artifactId = 'ffmpegplayer'
                version = '1.0.0.6'
            }
        }
    }
}
